import { Shield, Wrench, Clock, Check } from "lucide-react";

export const LAYANAN_CONTENT = {
  laptopServices: [
    {
      name: "Repaste Regular",
      price: "Rp 150.000",
      badge: null,
      material: "CryoFuze 5 / Arctic MX-6",
      desc: "Penggantian thermal paste standar menggunakan pasta berkualitas tinggi. Solusi terbaik untuk laptop yang mulai overheat akibat pasta lama yang mengering.",
      includes: [
        "Buka dan bersih heatsink",
        "Aplikasi pasta baru",
        "Test suhu setelah pemasangan",
        "Garansi 3 bulan",
      ],
    },
    {
      name: "Repaste Phase Change",
      price: "Rp 180.000",
      badge: null,
      material: "PTM 7950 / ID-Cooling PTM2",
      desc: "Menggunakan material phase change yang lebih tahan lama dan konduksi panas lebih efisien. Tidak perlu diganti berkala seperti pasta biasa.",
      includes: [
        "Buka dan bersih heatsink",
        "Aplikasi phase change material",
        "Test suhu & benchmark",
        "Garansi 6 bulan",
      ],
    },
    {
      name: "Repaste Liquid Metal",
      price: "Rp 200.000",
      badge: null,
      material: "Conductonaut / Thermal Grizzly (128 W/mK)",
      desc: "Konduktivitas tertinggi untuk performa pendinginan ekstrem. Ideal untuk laptop gaming dan workstation yang butuh suhu paling optimal.",
      includes: [
        "Persiapan & isolasi area sensitif",
        "Aplikasi liquid metal presisi",
        "Benchmark suhu sebelum-sesudah",
        "Garansi 6 bulan",
      ],
    },
    {
      name: "Repaste VRAM / VRM",
      price: "Rp 50.000",
      badge: null,
      material: "Thermal Putty / Pad Berkualitas",
      desc: "Penggantian thermal putty pada area VRAM dan VRM untuk mencegah GPU throttling dan menjaga performa grafis tetap stabil.",
      includes: [
        "Ganti thermal pad VRAM",
        "Ganti thermal pad VRM",
        "Test stabilitas GPU",
        "Garansi 3 bulan",
      ],
    },
    {
      name: "Cleaning Keyboard Eksternal",
      price: "Rp 80.000",
      badge: null,
      material: "—",
      desc: "Pembersihan menyeluruh keycaps dan plate keyboard dari debu, kerak, dan kotoran yang menumpuk. Keyboard kembali terasa seperti baru.",
      includes: [
        "Bongkar keycaps",
        "Cuci dan keringkan",
        "Bersih plate & PCB",
        "Pasang kembali rapi",
      ],
    },
    {
      name: "Deepclean Phase Change",
      price: "Rp 230.000",
      badge: "Paling Populer",
      material: "PTM 7950 + Full Cleaning Kit",
      desc: "Paket terlengkap: cleaning komprehensif seluruh komponen laptop PLUS repaste dengan phase change material. Hasilnya seperti laptop baru.",
      includes: [
        "Bersih fan, heatsink, body dalam",
        "Repaste PTM 7950",
        "Bersih layar & keyboard luar",
        "Test menyeluruh semua komponen",
        "Garansi 6 bulan",
      ],
    },
    {
      name: "Deepclean Liquid Metal",
      price: "Rp 250.000",
      badge: null,
      material: "Liquid Metal + Full Cleaning Kit",
      desc: "Paket premium: deep clean lengkap keyboard, layar, palmrest, dan semua komponen internal PLUS repaste liquid metal untuk performa puncak.",
      includes: [
        "Deep clean seluruh body & internal",
        "Repaste liquid metal presisi",
        "Bersih keyboard, layar, palmrest",
        "Benchmark & test komprehensif",
        "Garansi 6 bulan",
      ],
    },
    {
      name: "Special Request",
      price: "Hubungi Kami",
      badge: null,
      material: "Disesuaikan",
      desc: "Kebutuhan khusus yang tidak ada di daftar? Kami terbuka untuk layanan kustom sesuai kondisi spesifik laptop atau PC Anda.",
      includes: [
        "Konsultasi kebutuhan",
        "Estimasi biaya transparan",
        "Penanganan kasus khusus",
        "Garansi disesuaikan",
      ],
    },
  ],
  pcServices: [
    {
      name: "PC Repaste",
      price: "Rp 220.000",
      badge: null,
      material: "Arctic MX-6 / Phase Change",
      desc: "Penggantian thermal paste untuk PC desktop. Mengatasi overheat prosesor dan menjaga stabilitas sistem di semua brand dan socket.",
      includes: [
        "Buka dan bersih heatsink CPU",
        "Aplikasi pasta baru",
        "Test suhu idle & load",
        "Garansi 3 bulan",
      ],
    },
    {
      name: "Instal Ulang OS",
      price: "Rp 75.000",
      badge: null,
      material: "—",
      desc: "Instalasi sistem operasi bersih (fresh install) untuk Windows 10/11 atau Linux. Termasuk driver dasar agar langsung bisa digunakan.",
      includes: [
        "Format & instalasi OS bersih",
        "Instal driver dasar",
        "Aktivasi (jika Anda punya lisensi)",
        "Test fungsionalitas sistem",
      ],
    },
    {
      name: "Jasa Rakit PC",
      price: "Rp 150.000",
      badge: null,
      material: "—",
      desc: "Perakitan PC dari komponen yang Anda sediakan sendiri. Dikerjakan rapi dan benar oleh teknisi berpengalaman dengan cable management standar.",
      includes: [
        "Pasang semua komponen",
        "Cable management rapi",
        "BIOS setup & POST test",
        "Instal OS (opsional, +75K)",
      ],
    },
  ],
  guarantees: [
    { icon: Shield, text: "Garansi 3–6 bulan untuk setiap layanan" },
    { icon: Wrench, text: "Dikerjakan di depan Anda — penuh transparansi" },
    { icon: Clock, text: "Selesai dalam 1–2 jam untuk kebanyakan kasus" },
    { icon: Check, text: "Diagnosa gratis sebelum memutuskan layanan" },
  ],
  notes: [
    "Harga di atas belum termasuk spare part jika diperlukan. Estimasi part diberikan sebelum pengerjaan.",
    "Diagnosa gratis untuk semua jenis kerusakan — tidak ada kewajiban melanjutkan ke servis.",
    "Home visit tersedia untuk area Bandung — jadwalkan via WhatsApp.",
    "Pembayaran dilakukan setelah pekerjaan selesai dan Anda puas.",
  ],
} as const;
