import { Shield, Wrench, Clock, Check } from "lucide-react";

export const LAYANAN_CONTENT = {
  laptopServices: [
    {
      name: "Repaste Premium",
      price: "Rp 120.000",
      badge: null,
      material: "CryoFuze 5 / Arctic MX-6",
      desc: "Repasta menggunakan bahan cair terbaik dengan CryoFuze 5 / Arctic MX-6, bahan terbaik untuk suhu lebih adem.",
      includes: [
        "Buka dan bersih heatsink",
        "Aplikasi pasta baru",
        "Test suhu setelah pemasangan",
        "Garansi 7 hari",
      ],
    },
    {
      name: "Repaste Phase change",
      price: "Rp 170.000",
      badge: null,
      material: "PTM 7950 / ID-Cooling PTM2",
      desc: "Repasta menggunakan bahan phase change terbaik di kelasnya! Opsi pasta: PTM 7950 by Honeywell & ID-Cooling PTM2 - solusi suhu adem maksimal dengan umur yang lebih panjang.",
      includes: [
        "Buka dan bersih heatsink",
        "Aplikasi phase change material",
        "Test suhu & benchmark",
        "Garansi 7 hari",
      ],
    },
    {
      name: "Repaste Liquid Metal",
      price: "Rp 200.000",
      badge: null,
      material: "Conductonaut / Thermal Grizzly (128 W/mK)",
      desc: "Repaste dengan Liquid Metal terbaik di kelasnya! Konduktivitas tinggi (128 W/mK) untuk pendinginan ekstrem.",
      includes: [
        "Persiapan & isolasi area sensitif",
        "Aplikasi liquid metal presisi",
        "Benchmark suhu sebelum-sesudah",
        "Garansi 7 hari",
      ],
    },
    {
      name: "Repaste vram/vrm",
      price: "Rp 50.000",
      badge: null,
      material: "Thermal Putty / Pad Berkualitas",
      desc: "Repasta bagian VRAM/VRM menggunakan thermal putty performa terbaik.",
      includes: [
        "Ganti thermal pad/putty VRAM",
        "Ganti thermal pad/putty VRM",
        "Test stabilitas GPU",
        "Garansi 7 hari",
      ],
    },
    {
      name: "Cleaning Keyboard ext",
      price: "Rp 100.000*",
      badge: null,
      material: "—",
      desc: "Cleaning keyboard mechanical, membersihkan kerak yang menempel pada keycaps (cuci) dan plate keyboard.",
      includes: [
        "Bongkar keycaps",
        "Cuci dan keringkan",
        "Bersih plate & PCB",
        "Pasang kembali rapi",
      ],
    },
    {
      name: "Special req",
      price: "Hubungi Kami",
      badge: null,
      material: "Disesuaikan",
      desc: "Sesuaikan dengan kebutuhanmu!",
      includes: [
        "Konsultasi kebutuhan",
        "Estimasi biaya transparan",
        "Penanganan kasus khusus",
        "Garansi disesuaikan",
      ],
    },
  ],
  paketLaptopServices: [
    {
      name: "Deepclean Phase Change",
      price: "Rp 220.000",
      badge: "Paling Populer",
      material: "PTM 7950 + Full Cleaning Kit",
      desc: "Repasta menggunakan bahan phase change terbaik di kelasnya! berserta cleaning bagian body laptop yang mencakup keyboard, layar dan palmrest.",
      includes: [
        "Bersih fan, heatsink, body dalam",
        "Repaste PTM 7950",
        "Bersih keyboard, layar, palmrest",
        "Test suhu & benchmark",
        "Garansi 7 hari",
      ],
    },
    {
      name: "Deepclean Liquid Metal",
      price: "Rp 250.000",
      badge: null,
      material: "Liquid Metal + Full Cleaning Kit",
      desc: "Repasta menggunakan bahan Liquid metal berserta cleaning bagian body laptop yang mencakup keyboard, layar dan palmrest.",
      includes: [
        "Deep clean seluruh body & internal",
        "Repaste liquid metal presisi",
        "Bersih keyboard, layar, palmrest",
        "Benchmark & test komprehensif",
        "Garansi 7 hari",
      ],
    },
    {
      name: "Special req",
      price: "Hubungi Kami",
      badge: null,
      material: "Disesuaikan",
      desc: "Sesuaikan dengan kebutuhanmu!",
      includes: [
        "Konsultasi kebutuhan",
        "Estimasi biaya transparan",
        "Penanganan kasus khusus",
        "Garansi disesuaikan",
      ],
    },
  ],
  pcServices: [
    {
      name: "PC Repaste",
      price: "Rp 220.000",
      badge: null,
      material: "Arctic MX-6 / Phase Change",
      desc: "Penggantian thermal paste untuk PC desktop. Mengatasi overheat prosesor dan menjaga stabilitas sistem di semua brand dan socket.",
      includes: [
        "Buka dan bersih heatsink CPU",
        "Aplikasi pasta baru",
        "Test suhu idle & load",
        "Garansi 7 hari",
      ],
    },
    {
      name: "Instal Ulang OS",
      price: "Rp 75.000",
      badge: null,
      material: "—",
      desc: "Instalasi sistem operasi bersih (fresh install) untuk Windows 10/11 atau Linux. Termasuk driver dasar agar langsung bisa digunakan.",
      includes: [
        "Format & instalasi OS bersih",
        "Instal driver dasar",
        "Aktivasi (jika Anda punya lisensi)",
        "Test fungsionalitas sistem",
      ],
    },
    {
      name: "Jasa Rakit PC",
      price: "Rp 150.000",
      badge: null,
      material: "—",
      desc: "Perakitan PC dari komponen yang Anda sediakan sendiri. Dikerjakan rapi dan benar oleh teknisi berpengalaman dengan cable management standar.",
      includes: [
        "Pasang semua komponen",
        "Cable management rapi",
        "BIOS setup & POST test",
        "Instal OS (opsional, +75K)",
      ],
    },
  ],
  guarantees: [
    { icon: Shield, text: "Garansi 7 hari untuk setiap layanan" },
    { icon: Wrench, text: "Dikerjakan di depan Anda — penuh transparansi" },
    { icon: Clock, text: "Selesai dalam 1–2 jam untuk kebanyakan kasus" },
    { icon: Check, text: "Diagnosa gratis sebelum memutuskan layanan" },
  ],
  notes: [
    "Harga di atas belum termasuk spare part jika diperlukan. Estimasi part diberikan sebelum pengerjaan.",
    "Diagnosa gratis untuk semua jenis kerusakan — tidak ada kewajiban melanjutkan ke servis.",
    "Home visit tersedia untuk area Bandung — jadwalkan via WhatsApp.",
    "Pembayaran dilakukan setelah pekerjaan selesai dan Anda puas.",
  ],
} as const;
