"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _hero from './hero.bones.json'
import _problem_awareness from './problem-awareness.bones.json'
import _services from './services.bones.json'
import _features from './features.bones.json'
import _how_it_works from './how-it-works.bones.json'
import _gallery from './gallery.bones.json'
import _testimonials from './testimonials.bones.json'
import _faq from './faq.bones.json'
import _cta from './cta.bones.json'

configureBoneyard({"color":"#e5e5e5","darkColor":"#1a1a2e","animate":"shimmer","shimmerColor":"#ebebeb","darkShimmerColor":"#2a2a3e","speed":"1.5s"})

registerBones({
  "hero": _hero,
  "problem-awareness": _problem_awareness,
  "services": _services,
  "features": _features,
  "how-it-works": _how_it_works,
  "gallery": _gallery,
  "testimonials": _testimonials,
  "faq": _faq,
  "cta": _cta,
})
